runtime: nodejs20
env: standard
manual_scaling:
  instances: 1
env_variables:
  API_KEY: '${API_KEY}'
  AUTH_DOMAIN: '${AUTH_DOMAIN}'
  PROJECT_ID: '${PROJECT_ID}'
  STORAGE_BUCKET: '${STORAGE_BUCKET}'
  MESSAGING_SENDER_ID: '${MESSAGING_SENDER_ID}'
  APP_ID: '${APP_ID}'
  DATABASE_URL: '${DATABASE_URL}'